# Generated by Django 2.1.2 on 2018-11-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181022_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='无锡', max_length=100),
            preserve_default=False,
        ),
    ]
