# Generated by Django 2.1.2 on 2018-10-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='travel_date',
            new_name='travel_date_time',
        ),
    ]
