# Generated by Django 2.1.2 on 2018-10-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_auto_20181024_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='expend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
