# Generated by Django 2.1.2 on 2018-10-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0004_auto_20181024_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='expend',
            field=models.FloatField(null=True),
        ),
    ]
