# Generated by Django 2.1.2 on 2018-10-24 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181022_0510'),
        ('point', '0005_auto_20181024_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='post.Post'),
            preserve_default=False,
        ),
    ]
