# Generated by Django 2.1.2 on 2018-10-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0006_point_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='travel_date_time',
            field=models.DateTimeField(),
        ),
    ]
