# Generated by Django 2.1.2 on 2018-11-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181022_0510'),
        ('point', '0007_auto_20181026_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='post',
        ),
        migrations.AddField(
            model_name='point',
            name='post',
            field=models.ManyToManyField(related_name='point', to='post.Post'),
        ),
    ]
