# Generated by Django 2.1.2 on 2018-11-07 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_location'),
        ('point', '0008_auto_20181101_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='post',
        ),
        migrations.AddField(
            model_name='point',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='post.Post'),
            preserve_default=False,
        ),
    ]
