# Generated by Django 2.1.2 on 2018-11-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0010_auto_20181108_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='travel_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
