# Generated by Django 2.1.2 on 2018-10-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_profile_avartar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avartar',
            field=models.ImageField(blank=True, upload_to='userprofile/avartar/<built-in function id>'),
        ),
    ]
