# Generated by Django 2.1.2 on 2018-10-13 07:44

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20181013_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avartar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=userprofile.models.user_directory_path, verbose_name='头像'),
        ),
    ]
